-- ========================================
-- MIGRATE TOURS DATA TO SUPABASE
-- ========================================
-- Copy ALL of this SQL and paste it in:
-- https://supabase.com/dashboard/project/lmpvkxnudhyxjigugnzj/sql/new
-- Then click "Run" button
-- ========================================

-- Tour 1: 5 Days Wildlife Safari
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('5 Days Tanzania Wildlife Safari', '5-days-wildlife', 'Wildlife Safari', 'A classic Northern Circuit safari covering Tarangire, Serengeti, and Ngorongoro', 'A classic Northern Circuit safari covering Tarangire, Serengeti, and Ngorongoro. Best for first-time visitors seeking a wildlife-focused experience.', '["First-time visitors", "Wildlife focus"]'::jsonb, '5 days / 4 nights', 'Arusha', '["Big cats in Serengeti", "Ngorongoro Crater game drive", "Iconic baobabs + elephants in Tarangire"]'::jsonb, '[{"day": 1, "title": "Arusha → Tarangire", "description": "Game drive + picnic lunch", "overnight": "Tarangire / Karatu"}, {"day": 2, "title": "Tarangire → Serengeti", "description": "Drive via Ngorongoro highlands. Afternoon game drive", "overnight": "Serengeti"}, {"day": 3, "title": "Serengeti (full day)", "description": "Sunrise option + full-day game drive", "overnight": "Serengeti"}, {"day": 4, "title": "Serengeti → Ngorongoro / Karatu", "description": "Morning game drive. Transfer to Karatu", "overnight": "Karatu"}, {"day": 5, "title": "Ngorongoro Crater → Arusha", "description": "Crater descent + game drive. Return to Arusha", "overnight": ""}]'::jsonb, '["Professional driver-guide", "Park fees", "Safari vehicle + fuel", "Meals as per itinerary", "Bottled water"]'::jsonb, '["International flights", "Visa + travel insurance", "Tips", "Alcoholic drinks"]'::jsonb, '/images/destinations/serengeti.jpg', 2450, 9.4, 87, 'Moderate', true, true, 1);

-- Tour 2: 9 Days Safari + Zanzibar
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('9 Days Tanzania Safari + Zanzibar Beach', '9-days-safari-zanzibar', 'Safari & Beach', 'Complete Tanzania experience combining wildlife safari with beach relaxation', 'The ultimate Tanzania adventure combining the best wildlife destinations with pristine Zanzibar beaches. Perfect for honeymooners and those seeking variety.', '["Honeymooners", "Beach lovers", "Complete experience"]'::jsonb, '9 days / 8 nights', 'Arusha → Zanzibar', '["Serengeti wildlife", "Ngorongoro Crater", "Zanzibar Stone Town", "Beach relaxation"]'::jsonb, '[{"day": 1, "title": "Arusha → Tarangire", "description": "Game drive", "overnight": "Tarangire"}, {"day": 2, "title": "Tarangire → Serengeti", "description": "Afternoon game drive", "overnight": "Serengeti"}, {"day": 3, "title": "Serengeti full day", "description": "Full day game drive", "overnight": "Serengeti"}, {"day": 4, "title": "Serengeti → Ngorongoro", "description": "Morning game drive, transfer", "overnight": "Karatu"}, {"day": 5, "title": "Ngorongoro Crater", "description": "Crater tour", "overnight": "Arusha"}, {"day": 6, "title": "Fly to Zanzibar", "description": "Beach time", "overnight": "Zanzibar"}, {"day": 7, "title": "Zanzibar", "description": "Beach day", "overnight": "Zanzibar"}, {"day": 8, "title": "Stone Town Tour", "description": "Cultural tour", "overnight": "Zanzibar"}, {"day": 9, "title": "Departure", "description": "Fly home", "overnight": ""}]'::jsonb, '["All park fees", "Internal flights", "Accommodation", "Meals on safari"]'::jsonb, '["International flights", "Visa", "Travel insurance"]'::jsonb, '/images/destinations/zanzibar-beach.jpg', 4200, 9.6, 124, 'Moderate', true, true, 2);

-- Tour 3: Kilimanjaro Trekking
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('Mount Kilimanjaro - Machame Route', 'kilimanjaro-trekking', 'Mountain Trekking', 'Conquer Africa''s highest peak via the scenic Machame route', 'Challenge yourself to summit Mount Kilimanjaro (5,895m) via the popular Machame route. Known as the "Whiskey Route", it offers stunning scenery and excellent acclimatization.', '["Adventure seekers", "Experienced hikers", "Bucket list travelers"]'::jsonb, '7 days / 6 nights', 'Moshi → Moshi', '["Uhuru Peak summit", "Diverse ecosystems", "Experienced guides"]'::jsonb, '[{"day": 1, "title": "Machame Gate to Machame Camp", "description": "Rainforest trek", "overnight": "Machame Camp"}, {"day": 2, "title": "Machame to Shira Camp", "description": "Moors and heath", "overnight": "Shira Camp"}, {"day": 3, "title": "Shira to Barranco", "description": "Via Lava Tower", "overnight": "Barranco Camp"}, {"day": 4, "title": "Barranco to Karanga", "description": "Barranco Wall", "overnight": "Karanga Camp"}, {"day": 5, "title": "Karanga to Barafu", "description": "Base camp", "overnight": "Barafu Camp"}, {"day": 6, "title": "Summit day", "description": "Uhuru Peak, descend to Mweka", "overnight": "Mweka Camp"}, {"day": 7, "title": "Mweka to Gate", "description": "Descend through rainforest", "overnight": ""}]'::jsonb, '["Professional guides", "Park fees", "Camping equipment", "All meals on mountain"]'::jsonb, '["International flights", "Visa", "Gear rental", "Tips"]'::jsonb, '/images/destinations/kilimanjaro.jpg', 2800, 9.7, 203, 'Challenging', true, true, 3);

-- Tour 4: 6 Day Northern Circuit
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('6 Days Northern Circuit Safari', '6-day-northern-circuit', 'Wildlife Safari', 'Extended Northern Circuit covering all major parks', 'Comprehensive wildlife safari covering Tarangire, Serengeti, Ngorongoro, and Lake Manyara. Ideal for wildlife enthusiasts wanting more time in each location.', '["Wildlife photographers", "Nature lovers", "First-time safari"]'::jsonb, '6 days / 5 nights', 'Arusha', '["All Big Five", "Lake Manyara flamingos", "Extended Serengeti time"]'::jsonb, '[{"day": 1, "title": "Arusha → Lake Manyara", "description": "Game drive", "overnight": "Manyara"}, {"day": 2, "title": "Manyara → Serengeti", "description": "Afternoon game drive", "overnight": "Serengeti"}, {"day": 3, "title": "Serengeti full day", "description": "Full day exploration", "overnight": "Serengeti"}, {"day": 4, "title": "Serengeti", "description": "Morning and afternoon drives", "overnight": "Serengeti"}, {"day": 5, "title": "Serengeti → Ngorongoro", "description": "Transfer", "overnight": "Karatu"}, {"day": 6, "title": "Ngorongoro → Arusha", "description": "Crater tour, return", "overnight": ""}]'::jsonb, '["Professional guide", "All park fees", "Safari vehicle", "Meals and accommodation"]'::jsonb, '["Flights", "Visa", "Insurance", "Personal expenses"]'::jsonb, '/images/destinations/tarangire.jpg', 3100, 9.5, 156, 'Moderate', true, true, 4);

-- Tour 5: 4 Day Zanzibar Beach
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('4 Days Zanzibar Beach Escape', '4-day-zanzibar-beach', 'Beach Holiday', 'Relaxing beach getaway in tropical Zanzibar', 'Unwind on pristine white sand beaches, explore historic Stone Town, and enjoy crystal-clear waters. Perfect beach relaxation after a safari adventure.', '["Beach lovers", "Couples", "Relaxation seekers"]'::jsonb, '4 days / 3 nights', 'Zanzibar', '["Nungwi Beach", "Stone Town heritage", "Snorkeling", "Spice tours"]'::jsonb, '[{"day": 1, "title": "Arrival in Zanzibar", "description": "Transfer to beach resort", "overnight": "Nungwi"}, {"day": 2, "title": "Beach Day", "description": "Relaxation and water sports", "overnight": "Nungwi"}, {"day": 3, "title": "Stone Town & Spice Tour", "description": "Cultural excursion", "overnight": "Nungwi"}, {"day": 4, "title": "Departure", "description": "Fly home", "overnight": ""}]'::jsonb, '["Beach resort accommodation", "Airport transfers", "Breakfast daily", "Stone Town tour"]'::jsonb, '["International flights", "Lunch and dinner", "Water sports fees"]'::jsonb, '/images/destinations/zanzibar.jpg', 1200, 9.2, 98, 'Easy', true, false, 5);

-- Tour 6: 3 Day Luxury Safari
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('3 Days Luxury Tanzania Safari', '3-day-luxury-safari', 'Luxury Safari', 'Short but premium safari experience in luxury lodges', 'Experience the best of Tanzania wildlife in style with luxury accommodation, private game drives, and gourmet dining. Perfect for those with limited time.', '["Luxury travelers", "Short time", "Special occasions"]'::jsonb, '3 days / 2 nights', 'Arusha', '["Luxury lodges", "Private game drives", "Gourmet dining"]'::jsonb, '[{"day": 1, "title": "Arusha → Ngorongoro", "description": "Scenic drive, afternoon crater rim", "overnight": "Ngorongoro Luxury Lodge"}, {"day": 2, "title": "Ngorongoro Crater", "description": "Full day crater tour", "overnight": "Ngorongoro Luxury Lodge"}, {"day": 3, "title": "Return to Arusha", "description": "Morning game drive en route", "overnight": ""}]'::jsonb, '["Luxury lodge accommodation", "Private guide and vehicle", "All meals", "Premium drinks", "Park fees"]'::jsonb, '["International flights", "Visa", "Gratuities"]'::jsonb, '/images/destinations/luxury-safari.jpg', 4500, 9.8, 67, 'Easy', true, true, 6);

-- Tour 7: 7 Day Great Migration
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('7 Days Great Migration Safari', '7-day-great-migration', 'Migration Safari', 'Witness the spectacular wildebeest migration', 'Time your safari to witness one of nature's greatest spectacles - the Great Migration. Over 2 million wildebeest, zebras, and gazelles crossing the Serengeti.', '["Wildlife enthusiasts", "Photographers", "Nature lovers"]'::jsonb, '7 days / 6 nights', 'Arusha', '["River crossings", "Predator action", "Massive herds"]'::jsonb, '[{"day": 1, "title": "Arusha → Tarangire", "description": "Game drive", "overnight": "Tarangire"}, {"day": 2, "title": "Tarangire → Serengeti", "description": "Drive and afternoon drive", "overnight": "Serengeti"}, {"day": 3, "title": "Serengeti migration zone", "description": "Full day tracking herds", "overnight": "Serengeti"}, {"day": 4, "title": "Serengeti", "description": "Migration viewing", "overnight": "Serengeti"}, {"day": 5, "title": "Serengeti", "description": "Continued migration tracking", "overnight": "Serengeti"}, {"day": 6, "title": "Serengeti → Ngorongoro", "description": "Transfer", "overnight": "Karatu"}, {"day": 7, "title": "Ngorongoro → Arusha", "description": "Crater tour, return", "overnight": ""}]'::jsonb, '["Expert migration guide", "All park fees", "Accommodation", "Meals on safari"]'::jsonb, '["International flights", "Visa", "Travel insurance"]'::jsonb, '/images/destinations/migration.jpg', 4800, 9.9, 189, 'Moderate', true, true, 7);

-- Tour 8: 5 Day Family Adventure
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('5 Days Family Safari Adventure', '5-day-family-adventure', 'Family Safari', 'Family-friendly safari with activities for all ages', 'Specially designed family safari with kid-friendly activities, shorter drives, and educational experiences. Create unforgettable memories with your family.', '["Families with kids", "Educational travel", "Multi-generational"]'::jsonb, '5 days / 4 nights', 'Arusha', '["Kid-friendly guides", "Cultural visits", "Short drives"]'::jsonb, '[{"day": 1, "title": "Arusha → Lake Manyara", "description": "Easy game drive", "overnight": "Manyara"}, {"day": 2, "title": "Manyara → Serengeti", "description": "Scenic drive", "overnight": "Serengeti"}, {"day": 3, "title": "Serengeti family day", "description": "Wildlife tracking activity", "overnight": "Serengeti"}, {"day": 4, "title": "Serengeti → Ngorongoro", "description": "Maasai village visit", "overnight": "Karatu"}, {"day": 5, "title": "Ngorongoro → Arusha", "description": "Crater tour, return", "overnight": ""}]'::jsonb, '["Family-friendly lodges", "Kid activities", "All meals", "Park fees", "Cultural visits"]'::jsonb, '["Flights", "Visa", "Insurance", "Optional activities"]'::jsonb, '/images/destinations/family-safari.jpg', 2900, 9.3, 74, 'Easy', true, false, 8);

-- Tour 9: 8 Day Photography Safari
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('8 Days Photography Safari', '8-day-photography-safari', 'Photography Safari', 'Professional photography-focused safari experience', 'Designed for photography enthusiasts with expert guides, optimal positioning for shots, and extended time at wildlife sightings. Capture stunning African wildlife.', '["Photographers", "Nature enthusiasts", "Advanced amateurs"]'::jsonb, '8 days / 7 nights', 'Arusha', '["Photo expert guide", "Optimal lighting times", "Extended wildlife viewing"]'::jsonb, '[{"day": 1, "title": "Arrival Arusha", "description": "Briefing and prep", "overnight": "Arusha"}, {"day": 2, "title": "Arusha → Tarangire", "description": "Afternoon photography", "overnight": "Tarangire"}, {"day": 3, "title": "Tarangire → Serengeti", "description": "Game drive with photo stops", "overnight": "Serengeti"}, {"day": 4, "title": "Serengeti photography", "description": "Full day shooting", "overnight": "Serengeti"}, {"day": 5, "title": "Serengeti", "description": "Sunrise and full day", "overnight": "Serengeti"}, {"day": 6, "title": "Serengeti", "description": "Continued photography", "overnight": "Serengeti"}, {"day": 7, "title": "Serengeti → Ngorongoro", "description": "Transfer", "overnight": "Karatu"}, {"day": 8, "title": "Ngorongoro → Arusha", "description": "Crater photography, return", "overnight": ""}]'::jsonb, '["Professional photo guide", "All park fees", "Accommodation", "Meals", "Photo equipment tips"]'::jsonb, '["Camera gear", "International flights", "Visa", "Insurance"]'::jsonb, '/images/destinations/photography-safari.jpg', 5200, 9.7, 112, 'Moderate', true, true, 9);

-- Tour 10: 10 Day Grand Tanzania
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('10 Days Grand Tanzania Explorer', '10-day-grand-tanzania', 'Grand Safari', 'Comprehensive Tanzania experience covering all highlights', 'The ultimate Tanzania adventure covering northern parks, cultural experiences, and beach relaxation. Perfect for first-time visitors wanting the complete experience.', '["Complete experience", "First-time visitors", "Luxury seekers"]'::jsonb, '10 days / 9 nights', 'Arusha → Zanzibar', '["All major parks", "Cultural immersion", "Beach extension"]'::jsonb, '[{"day": 1, "title": "Arrival Arusha", "description": "Welcome", "overnight": "Arusha"}, {"day": 2, "title": "Arusha → Tarangire", "description": "Game drive", "overnight": "Tarangire"}, {"day": 3, "title": "Tarangire → Serengeti", "description": "Afternoon drive", "overnight": "Serengeti"}, {"day": 4, "title": "Serengeti", "description": "Full day", "overnight": "Serengeti"}, {"day": 5, "title": "Serengeti", "description": "Extended exploration", "overnight": "Serengeti"}, {"day": 6, "title": "Serengeti → Ngorongoro", "description": "Transfer", "overnight": "Karatu"}, {"day": 7, "title": "Ngorongoro Crater", "description": "Crater tour", "overnight": "Arusha"}, {"day": 8, "title": "Fly to Zanzibar", "description": "Beach time", "overnight": "Zanzibar"}, {"day": 9, "title": "Zanzibar", "description": "Beach and culture", "overnight": "Zanzibar"}, {"day": 10, "title": "Departure", "description": "Fly home", "overnight": ""}]'::jsonb, '["All accommodations", "Internal flights", "All park fees", "Meals on safari", "Beach resort"]'::jsonb, '["International flights", "Visa", "Travel insurance"]'::jsonb, '/images/destinations/grand-tanzania.jpg', 6500, 9.8, 145, 'Moderate', true, true, 10);

-- Tour 11: 6 Day Bush & Beach
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('6 Days Bush & Beach Combo', '6-day-bush-beach', 'Safari & Beach', 'Perfect combination of wildlife safari and beach relaxation', 'Experience the best of both worlds - exciting wildlife game drives followed by relaxing beach days in Zanzibar. Ideal balance of adventure and relaxation.', '["Best of both worlds", "Couples", "Honeymooners"]'::jsonb, '6 days / 5 nights', 'Arusha → Zanzibar', '["Serengeti wildlife", "Ngorongoro Crater", "Zanzibar beaches"]'::jsonb, '[{"day": 1, "title": "Arusha → Serengeti", "description": "Fly in, afternoon drive", "overnight": "Serengeti"}, {"day": 2, "title": "Serengeti", "description": "Full day game drive", "overnight": "Serengeti"}, {"day": 3, "title": "Serengeti → Ngorongoro", "description": "Morning drive, transfer", "overnight": "Karatu"}, {"day": 4, "title": "Ngorongoro → Arusha → Zanzibar", "description": "Crater tour, fly to Zanzibar", "overnight": "Zanzibar"}, {"day": 5, "title": "Zanzibar beach day", "description": "Relaxation", "overnight": "Zanzibar"}, {"day": 6, "title": "Departure", "description": "Fly home", "overnight": ""}]'::jsonb, '["Internal flights", "Park fees", "Accommodation", "Beach resort", "Meals on safari"]'::jsonb, '["International flights", "Visa", "Insurance", "Beach activities"]'::jsonb, '/images/destinations/bush-beach.jpg', 3800, 9.5, 93, 'Moderate', true, false, 11);

-- Tour 12: 4 Day Quick Safari
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('4 Days Quick Tanzania Safari', '4-day-quick-safari', 'Express Safari', 'Short but comprehensive safari for time-limited travelers', 'Maximize your wildlife experience in minimum time. Perfect for business travelers or those with tight schedules who still want to see the best of Tanzania.', '["Time-limited travelers", "Business travelers", "Quick getaway"]'::jsonb, '4 days / 3 nights', 'Arusha', '["Express highlights", "Ngorongoro Crater", "Serengeti taste"]'::jsonb, '[{"day": 1, "title": "Arusha → Lake Manyara", "description": "Game drive", "overnight": "Manyara"}, {"day": 2, "title": "Manyara → Serengeti", "description": "Afternoon game drive", "overnight": "Serengeti"}, {"day": 3, "title": "Serengeti → Ngorongoro", "description": "Morning drive, transfer", "overnight": "Karatu"}, {"day": 4, "title": "Ngorongoro → Arusha", "description": "Crater tour, return", "overnight": ""}]'::jsonb, '["Professional guide", "Park fees", "Accommodation", "Meals"]'::jsonb, '["International flights", "Visa", "Insurance"]'::jsonb, '/images/destinations/quick-safari.jpg', 1950, 9.1, 68, 'Easy', true, false, 12);

-- Tour 13: 12 Day Ultimate Tanzania
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('12 Days Ultimate Tanzania Experience', '12-day-ultimate-tanzania', 'Ultimate Safari', 'The most comprehensive Tanzania safari experience', 'The ultimate Tanzania adventure covering northern and southern parks, Kilimanjaro views, cultural experiences, and Zanzibar beaches. For those who want everything.', '["Ultimate experience", "Extended travel", "Luxury seekers"]'::jsonb, '12 days / 11 nights', 'Arusha → Zanzibar', '["All parks", "Kilimanjaro views", "Cultural immersion", "Beach luxury"]'::jsonb, '[{"day": 1, "title": "Arrival Arusha", "description": "Welcome", "overnight": "Arusha"}, {"day": 2, "title": "Arusha → Tarangire", "description": "Game drive", "overnight": "Tarangire"}, {"day": 3, "title": "Tarangire → Serengeti", "description": "Afternoon drive", "overnight": "Serengeti"}, {"day": 4, "title": "Serengeti", "description": "Full day", "overnight": "Serengeti"}, {"day": 5, "title": "Serengeti", "description": "Extended exploration", "overnight": "Serengeti"}, {"day": 6, "title": "Serengeti → Ngorongoro", "description": "Transfer", "overnight": "Karatu"}, {"day": 7, "title": "Ngorongoro Crater", "description": "Crater tour", "overnight": "Arusha"}, {"day": 8, "title": "Arusha → Kilimanjaro area", "description": "Scenic views", "overnight": "Moshi"}, {"day": 9, "title": "Cultural day", "description": "Maasai village, coffee tour", "overnight": "Moshi"}, {"day": 10, "title": "Fly to Zanzibar", "description": "Beach time", "overnight": "Zanzibar"}, {"day": 11, "title": "Zanzibar", "description": "Beach and culture", "overnight": "Zanzibar"}, {"day": 12, "title": "Departure", "description": "Fly home", "overnight": ""}]'::jsonb, '["All accommodations", "Internal flights", "All park fees", "All meals on safari", "Luxury beach resort", "Cultural tours"]'::jsonb, '["International flights", "Visa", "Travel insurance", "Optional activities"]'::jsonb, '/images/destinations/ultimate-tanzania.jpg', 8500, 9.9, 87, 'Moderate', true, true, 13);

-- Tour 14: 5 Day Budget Safari
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('5 Days Budget Camping Safari', '5-day-budget-safari', 'Budget Safari', 'Affordable camping safari covering major parks', 'Experience Tanzania's incredible wildlife on a budget with comfortable camping accommodation. Perfect for adventurous travelers who want maximum safari experience at minimum cost.', '["Budget travelers", "Adventurers", "Camping enthusiasts"]'::jsonb, '5 days / 4 nights', 'Arusha', '["Affordable pricing", "Camping experience", "All major parks"]'::jsonb, '[{"day": 1, "title": "Arusha → Tarangire", "description": "Game drive, camp setup", "overnight": "Tarangire Camp"}, {"day": 2, "title": "Tarangire → Serengeti", "description": "Afternoon drive", "overnight": "Serengeti Camp"}, {"day": 3, "title": "Serengeti full day", "description": "Full day game drive", "overnight": "Serengeti Camp"}, {"day": 4, "title": "Serengeti → Ngorongoro", "description": "Transfer", "overnight": "Karatu Camp"}, {"day": 5, "title": "Ngorongoro → Arusha", "description": "Crater tour, return", "overnight": ""}]'::jsonb, '["Camping equipment", "Park fees", "All meals", "Professional guide", "Safari vehicle"]'::jsonb, '["International flights", "Visa", "Insurance", "Sleeping bag rental"]'::jsonb, '/images/destinations/budget-safari.jpg', 1450, 9.0, 134, 'Moderate', true, false, 14);

-- Tour 15: 7 Day Honeymoon Luxury
INSERT INTO tours (name, slug, category, "shortDescription", overview, "bestFor", duration, "startEnd", highlights, itinerary, included, excluded, "imageUrl", "priceFrom", rating, "reviewCount", difficulty, "isActive", "isFeatured", "displayOrder") VALUES
('7 Days Luxury Honeymoon Safari & Beach', '7-day-honeymoon-luxury', 'Luxury Honeymoon', 'Romantic luxury safari and beach honeymoon package', 'Celebrate your love with the ultimate romantic getaway. Luxury tented camps, private game drives, champagne sunsets, and pristine beach resorts.', '["Honeymooners", "Couples", "Romantic getaway"]'::jsonb, '7 days / 6 nights', 'Arusha → Zanzibar', '["Luxury tented camps", "Private game drives", "Champagne experiences", "Beach villa"]'::jsonb, '[{"day": 1, "title": "Arrival Arusha", "description": "VIP transfer", "overnight": "Arusha luxury hotel"}, {"day": 2, "title": "Fly to Serengeti", "description": "Afternoon private game drive", "overnight": "Luxury tented camp"}, {"day": 3, "title": "Serengeti", "description": "Full day private safari", "overnight": "Luxury tented camp"}, {"day": 4, "title": "Serengeti → Zanzibar", "description": "Morning drive, fly to Zanzibar", "overnight": "Beach villa"}, {"day": 5, "title": "Zanzibar", "description": "Beach day, couples spa", "overnight": "Beach villa"}, {"day": 6, "title": "Zanzibar", "description": "Sunset dhow cruise", "overnight": "Beach villa"}, {"day": 7, "title": "Departure", "description": "Fly home", "overnight": ""}]'::jsonb, '["Luxury accommodations", "Internal flights", "Private game drives", "All meals", "Couples spa", "Champagne experiences"]'::jsonb, '["International flights", "Visa", "Travel insurance", "Optional activities"]'::jsonb, '/images/destinations/honeymoon-luxury.jpg', 7200, 9.9, 156, 'Easy', true, true, 15);
